// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihxbabhitdviuaiseaak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloeGJhYmhpdGR2aXVhaXNlYWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNjc5ODIsImV4cCI6MjA4NTk0Mzk4Mn0.37roOCbRH2aAZauZNYjWdXrKj2Hg2Tidx2uXFcX1bQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});